### ISSUE TITLE
Mala presentación de los mensajes

### ISSUE THREAD

**Issue by Wolfteinter** [dbetm/poli-bot#4]
Arreglar la presentación de los mensajes:

- [x] Que se respeten los saltos de línea.
- [x] Usar soft wrap para que no se tenga que activar el scroll horizontal en un mensaje.
- [x] Mostrar imágenes en los mensajes.
- [x] Los hipervínculos se pueden abrir en el navegador.
- [x] Hacer más grande el área de mensajes para los textos grandes,

**Comment by dbetm** [comment]
- [x] Normalizar los intents para que las respuestas se muestren respetando saltos de línea y enlaces.
